satori-fit-text: fix unit test flakiness
Try fixing this error:

```
⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯
Error: [vitest-worker]: Timeout calling "onTaskUpdate"
 ❯ Object.onTimeoutError ../../node_modules/.pnpm/vitest@3.1.1_@types+debug@4.1.12_@types+node@22.13.10_happy-dom@17.4.4_jiti@1.21.6_jsdom@26.0.0_yaml@2.7.0/node_modules/vitest/dist/chunks/rpc.DGgL5dw7.js:62:10
 ❯ Timeout._onTimeout ../../node_modules/.pnpm/vitest@3.1.1_@types+debug@4.1.12_@types+node@22.13.10_happy-dom@17.4.4_jiti@1.21.6_jsdom@26.0.0_yaml@2.7.0/node_modules/vitest/dist/chunks/index.68735LiX.js:55:41
 ❯ listOnTimeout node:internal/timers:594:17
 ❯ processTimers node:internal/timers:529:7
```